_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.8
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 14
                - 16
                - 23
                - 55
            "4": 3.11.8
            "5": 0.19.1
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
C:
    value: 10
architecture:
    value: |-
        DQN(
          (conv1): Conv2d(3, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (conv2): Conv2d(16, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (MSELoss): MSELoss()
          (fc1): Linear(in_features=2592, out_features=64, bias=True)
          (output): Linear(in_features=64, out_features=1, bias=True)
        )
batch_size:
    value: 32
learning_rate:
    value: 0.0001
